### ISSUE TITLE
SSR False

### ISSUE THREAD

**Issue by fvspn** [ahmetilhan24/persisted-state-vuex#12]
I need to use the plugins with ssr: false, otherwise, throw a error: window is not defined

https://prnt.sc/Naim4IHxhYSu

**Comment by ahmetilhan24** [comment]
Thank you for feedback. I'm starting to work on fixing the error. @fvspn

**Comment by ahmetilhn** [comment]
Supported for SSR and Nuxt projects.  I would be very happy if you follow and like.
