### ISSUE TITLE
not compatible with nuxt-auth

### ISSUE THREAD

**Issue by fvspn** [ahmetilhan24/persisted-state-vuex#16]
is this module compatible with  https://auth.nuxtjs.org/?

**Comment by ahmetilhan24** [comment]
Maalesef uyumlu değil :/

**Comment by ahmetilhn** [comment]
Sorry, not compatible

**Comment by fvspn** [comment]
is there a way to make it work?

**Comment by ahmetilhn** [comment]
Can you post the error output or a picture of the error?

**Comment by fvspn** [comment]
There are no errors, I just can't use the store, for example, if I change the value of some state property, when refreshing the page, everything goes back to 0.

Check this https://github.com/championswimmer/vuex-persist/issues/146
